name: Build and Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      Category:
        description: 'Choose a test tag'
        required: false
        default: 'All'
        type: choice
        options:
          - All
          - mytag
          - Smoke
      Project:
        description: 'Choose a project to run tests from'
        required: false
        default: 'All'
        type: choice
        options:
          - All
          - API.Tests
          - Data.Tests
          - Performance.Tests
          - UI.Tests

# TBD - Input choice between Production and Local environments
# TBD - Repository dispatch

jobs:
  Run-Tests:
    env:
      tag: ${{ github.event_name == 'workflow_dispatch' && inputs.Category || 'All' }}
      project: ${{ github.event_name == 'workflow_dispatch' && inputs.Project || 'All' }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      
    runs-on: ubuntu-latest

    steps:
    - name: Set test tag filtering based on input
      run: |
          if [ "${tag}" = "All" ] || [ "${tag}" = ""]; then
            echo "tag=" >> $GITHUB_ENV
          else
            echo "tag=--filter \"TestCategory=${tag}\"" >> $GITHUB_ENV
          fi
    - name: Set test project filtering based on input
      run: |
          if [ "${project}" = "All" ] || [ "${project}" = ""]; then
            echo "project=" >> $GITHUB_ENV
          else
            echo "project=${project}" >> $GITHUB_ENV
          fi

    - uses: actions/checkout@v4
    - name: Setup .NET projects
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Docker Image
      working-directory: ./CSharpTestFramework
      run: docker build -t csharp-tests .

    - name: Run tests in Docker container
      working-directory: ./CSharpTestFramework
      run: docker run --rm -e SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}" -e SUPABASE_URL="${{ secrets.SUPABASE_URL }}" -v "${PWD}/allure-results:/app/allure-results" -v "${PWD}/logs/Data.Tests:/app/Data.Tests/bin/Debug/net8.0/logs" -v "${PWD}/logs/UI.Tests:/app/UI.Tests/bin/Debug/net8.0/logs" -v "${PWD}/logs/API.Tests:/app/API.Tests/bin/Debug/net8.0/logs" -v "${PWD}/logs/Performance.Tests:/app/Performance.Tests/bin/Debug/net8.0/logs" csharp-tests

    - name: Load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.13
      if: always()
      with:
        gh_pages: gh-pages
        allure_results: CSharpTestFramework/allure-results
        allure_history: CSharpTestFramework/allure-history

    - name: Publish test report
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: CSharpTestFramework/allure-history

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
          CSharpTestFramework/logs/API.Tests/*.txt
          CSharpTestFramework/logs/Data.Tests/*.txt
          CSharpTestFramework/logs/Performance.Tests/*.txt
          CSharpTestFramework/logs/UI.Tests/*.txt
